module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['🧩', '🍉', '💜', '🌸', '🪴', '💊', '💫', '🍂', '🌟', '🎋', '😶‍🌫️', '🫀', '🧿', '👀', '🤖', '🚩', '🥰', '🗿', '💜', '💙', '🌝', '🖤', '💚'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/GYFkafbxbD8JHDCPzXPlIi',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: 'https://files.catbox.moe/fpyw9m.png',
    NEWSLETTER_JID: '120363406815628638@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: '𝓓𝓣𝓩 𝓝𝓞𝓥𝓐 𝚇 𝗠𝗗 MINI BOT 𝗩1',
    OWNER_NAME: 'DTZ DULA',
    OWNER_NUMBER: '94752978237',
    BOT_VERSION: '1.0.0',
    BOT_FOOTER: '> 𝓓𝓣𝓩 𝓝𝓞𝓥𝓐 𝚇 𝗠𝗗 𝗩1',
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029Vb6saRv6mYPEqp1ERR3N',
};
